---
- name: configure Worker node
  hosts: all
  tasks:

   - name: Register as user (someuser) with password (somepass) and auto-subscribe to available content.
     redhat_subscription:
      state: present
      username: ajay-kumar
      password: Ajay@6540
      auto_attach: true
      force_register: true
     tags: subscribe
   - name: subscribe
     shell: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-optional-rpms
     tags: repo

   - name: Turn off swap
     command: swapoff -a
     changed_when: true
     when: ansible_swaptotal_mb > 0

   - name: Disable swap
     lineinfile:
      path: '/etc/fstab'
      regexp: '\sswap\s'
      state: absent

   - name: Put SELinux in disable mode, logging actions that would be blocked.
     selinux:
      state: disabled

   - name: Disable firewalld
     systemd:
      name: firewalld
      state: stopped
      enabled: no

   - name: Load the required kernel modules
     modprobe:
      name: "{{ item }}"
      state: present
     with_items:
      - br_netfilter
      - overlay

   - name: Persist kernel module loading
     copy:
      dest: '/etc/modules-load.d/k8s.conf'
      content: |
       br_netfilter
       overlay
   - name: Tune sysctl parameters  in /proc and the sysctl file
     sysctl:
      name: "{{ item }}"
      value: '1'
      sysctl_set: yes
      state: present
     with_items:
      - net.ipv4.ip_forward
      - net.bridge.bridge-nf-call-iptables
      - net.bridge.bridge-nf-call-ip6tables

   - name: Add Kubernetes repository
     yum_repository:
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      name: "Kubernetes"
      state: present
      description: "Kubernetes Repository"
      gpgcheck: 0
      gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
      exclude: "kubelet kubeadm kubectl"
     tags: kube_repo

   - name: Add docker repository
     yum_repository:
      name: "Docker-CE"
      description: "Docker CE Stable"
      baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
      state: present
      gpgcheck: 0
      gpgkey: https://download.docker.com/linux/centos/gpg
     tags: docker_repo

   - name: remove app
     yum:
       name: "{{packg}}"
       state: absent
     vars:
      packg:
       - kubeadm
       - kubelet
       - kubectl
     tags: remove_app

   - name: Install required packages (docker, kubeadmn, kubectl, kubelet)
     yum:
      name: "{{ packages }}"
      disable_excludes: "Kubernetes"
     vars:
      packages:
       - kubelet-1.24.0-0
       - kubectl-1.24.0-0
       - docker-ce-20.10.18-3.el7
       - docker-ce-cli-20.10.18-3.el7
       - containerd.io
       - kubeadm-1.24.0-0
       - yum-versionlock
     tags: install_package

#   - name: install version lock package
#     yum:
#      name: yum-versionlock
#      state: latest

   - name: Apply version lock
     shell: yum versionlock add kubeadm kubectl kubelet docker-ce

   - name: Create a directory if it does not exist
     file:
      path: /etc/docker
      state: directory
      mode: '0755'

#   - name: Configure crictl to use docker
#     template:
#      src: /root/nitin/daemon.j2
#      dest: /etc/docker/daemon.json
#     notify:
#     - restart_docker
#     tags: docker

   - name: just force systemd to reread configs
     systemd:
      state: restarted
      daemon_reload: yes
      name: docker
     tags: docker

   - name: Enable and start the required services (docker, kubelet)
     systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
     with_items:
      - docker
      - kubelet
     tags: start_service

